name: Publish package

on:
  push:
    tags: ["*"]

permissions:
  contents: read
  packages: write

jobs:
  github-packages:
    name: Publish WASM package to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Set up GitHub Packages authentication
        uses: actions/setup-node@v4
        with:
          registry-url: https://npm.pkg.github.com
          scope: "@rilevera"
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build and test WASM
        run: make build
      - name: Publish package
        run: bun publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
